#!/bin/bash

# Linters
echo "Running isort"
python3 -m isort $(find ./src/**py)
echo "Running python black"
python3 -m black src
echo "Running pylint"
python3 -m pylint src
echo "Running flake8"
python3 -m flake8 src

# Unit test
python3  -m unittest src/discord_cage_bot_test.py
